services:
    App\Helper\Generic\FileHelper:
        public: true
        arguments:
            $kernel: "@kernel"
            $mediaDirectory: "%app.media_directory%"

    app.generic.file_helper:
        alias: App\Helper\Generic\FileHelper
        public: true