<?php

namespace App\Entity\Security;

use App\Entity\Security\ParticularAccesse;
use App\Entity\Security\Profil;
use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;
use App\Model\security\RollableInterface;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Description of Utilisateur
 *
 * @author Dadja
 * @ORM\Entity(repositoryClass="App\Repository\Security\UserRepository")
 */
class User extends BaseUser
{

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @var Profil
     *
     * @ORM\OneToOne(targetEntity="App\Entity\Security\Avatar")
     * @ORM\JoinColumn(name="avatar_id", nullable=true, referencedColumnName="id", nullable=true)
     */
    protected $avatar;

    /**
     * @var Profil
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Security\Profil")
     * @ORM\JoinColumn(name="profil_id", referencedColumnName="id", nullable=true)
     */
    protected $profil;

    /**
     * One Product has One Shipment.
     * @var ParticularAccesse
     *
     * @ORM\OneToOne(targetEntity="ParticularAccesse")
     * @ORM\JoinColumn(name="particular_access_id", referencedColumnName="id", nullable=true)
     */
    protected $paticularAccesse;
    
    /**
     * The constructor
     */
    public function __construct()
    {
        $this->enabled = true;
    }

    public function __toString()
    {
        return parent::__toString();
    }


    /**
     * 
     * @return int
     */
    public function getId() 
    {
        return $this->id;
    }



    /**
     * @inheritDoc
     */
    public function getRoles():array
    {
        return parent::getRoles(); // TODO: Change the autogenerated stub
    }

    /**
     * @return Profil
     */
    public function getProfil(): ?Profil
    {
        return $this->profil;
    }

    /**
     * @param Profil $profil
     * @return User
     */
    public function setProfil(?Profil $profil): User
    {
        $this->profil = $profil;
        return $this;
    }

    /**
     * @return ParticularAccesse
     */
    public function getPaticularAccesse(): ?ParticularAccesse
    {
        return $this->paticularAccesse;
    }

    /**
     * @param ParticularAccesse $paticularAccesse
     * @return User
     */
    public function setPaticularAccesse(?ParticularAccesse $paticularAccesse): User
    {
        $this->paticularAccesse = $paticularAccesse;
        return $this;
    }

    /**
     * @return \App\Entity\Security\Profil
     */
    public function getAvatar(): \App\Entity\Security\Profil
    {
        return $this->avatar;
    }

    /**
     * @param \App\Entity\Security\Profil $avatar
     * @return User
     */
    public function setAvatar(\App\Entity\Security\Profil $avatar): User
    {
        $this->avatar = $avatar;
        return $this;
    }


}
